version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT:-development}
    depends_on:
      - redis
    ports:
      - '8000:8000'
    environment:
      REDIS_URL: 'redis://redis:6379/0'
    volumes:
      - '.:/opt/app'
    command: [ "make", "run" ]

  redis:
    image: 'redis:6'
    ports:
      - '6379:6379'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
